In [2]:
import torch
import torchvision
import numpy as np

In [3]:
# Tensor Basis
# This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [4]:
# This is a 2-D tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [5]:
# The size of the tensors
print(a.shape)
print(a.size())
print(b.shape)
print(b.size())

torch.Size([3])
torch.Size([3])
torch.Size([4, 3])
torch.Size([4, 3])


In [6]:
# Get the height / number of rows of b tensor
print(b.shape[0])

4


In [10]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# or we can do
#c = torch.tensor([2,2,1], dtype = torch.float)
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [15]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
# or we can do
#c = torch.tensor([2,2,1], dtype = torch.double)
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [16]:
print(c.mean())
print(d.mean())

tensor(2.5833, dtype=torch.float64)
tensor(2.5833, dtype=torch.float64)


In [17]:
print(c.std())
print(d.std())

tensor(1.5050, dtype=torch.float64)
tensor(1.5050, dtype=torch.float64)


In [33]:
#Reshape
#Note: If one of the dimensions is -1, its size can e inferred
print(b)
print(b.shape)
print("\nb.view(-1,1):")
print(b.view(-1,1))
print("\nb.view(-1,2):")
print(b.view(-1,2))
print("\nb.view(12):")
print(b.view(12))
print("\nb.view(-1):")
print(b.view(-1))
print("\nb.view(3,4)")
print(b.view(3,4))

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])
torch.Size([4, 3])

b.view(-1,1):
tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])

b.view(-1,2):
tensor([[2, 1],
        [4, 3],
        [5, 4],
        [1, 2],
        [0, 4],
        [3, 2]])

b.view(12):
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])

b.view(-1):
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])

b.view(3,4)
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])


In [35]:
#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)

tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])


In [43]:
# We can even reshape 3D tensors
# Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channels, rows, columns)
three_dim = torch.randn(2,3,4)
print(three_dim)
print("\nthree_dim(view(2, 12))")
print(three_dim.view(2, 12))
print("\nthree_dim.view(2,-1)")
print(three_dim.view(2,-1))

tensor([[[-0.4453, -0.3976,  1.2583, -0.5768],
         [-1.1625, -0.2126, -0.6871, -0.4643],
         [-0.3391,  1.3170,  0.9472,  0.9708]],

        [[-0.1895, -0.2199, -0.1299,  1.1770],
         [-0.8983,  2.1682,  0.4821, -0.9502],
         [ 1.8974,  1.7913,  0.3898, -1.8203]]])

three_dim(view(2, 12))
tensor([[-0.4453, -0.3976,  1.2583, -0.5768, -1.1625, -0.2126, -0.6871, -0.4643,
         -0.3391,  1.3170,  0.9472,  0.9708],
        [-0.1895, -0.2199, -0.1299,  1.1770, -0.8983,  2.1682,  0.4821, -0.9502,
          1.8974,  1.7913,  0.3898, -1.8203]])

three_dim.view(2,-1)
tensor([[-0.4453, -0.3976,  1.2583, -0.5768, -1.1625, -0.2126, -0.6871, -0.4643,
         -0.3391,  1.3170,  0.9472,  0.9708],
        [-0.1895, -0.2199, -0.1299,  1.1770, -0.8983,  2.1682,  0.4821, -0.9502,
          1.8974,  1.7913,  0.3898, -1.8203]])


In [44]:
# Create a martrix with random numbers between 1 and 1
r = torch.rand(4, 4)
print(r)

tensor([[0.3290, 0.2107, 0.5204, 0.2168],
        [0.2591, 0.9871, 0.9499, 0.3070],
        [0.8580, 0.4211, 0.4405, 0.5132],
        [0.8342, 0.8987, 0.6044, 0.0651]])


In [46]:
# Create a matrix with random numbers taken from a normal distribution 
# with mean 0 and variance 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-0.2512, -0.7007,  0.5869,  2.6225],
        [ 0.1491,  2.0162, -0.2382, -2.3403],
        [-0.8968, -1.2754,  1.0643,  1.6481],
        [-0.8760,  1.3993, -1.2846, -1.3064]])
torch.float32


In [51]:
# Create a matrix with random numbers taken from a normal distribution 
# with mean 0 and variance 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-1.7672, -0.4486,  0.2094, -1.7813],
        [-1.7037, -0.1303,  0.2090, -2.3718],
        [-1.7970, -0.9790,  2.2273, -0.8103],
        [ 0.6536, -0.5837,  1.7950, -0.2548]])
torch.float32


In [56]:
# Create an array of 5 random integers from values 
# between 6 and 9 (exclusive of 10)
in_array = torch.randint(6,10,(5,))
print(in_array)
print(in_array.dtype)

tensor([7, 8, 7, 6, 8])
torch.int64


In [65]:
# Create a 2-D array (or matrix) of size 3x3 filled with
# random integers from values between 6 and 9 (exclusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[8, 8, 8],
        [8, 6, 8],
        [7, 7, 6]])


In [67]:
# Get the number of elements in in_array
print(torch.numel(in_array))
# Get the number of elements in in_array
print(torch.numel(in_array2))

5
9


In [69]:
# Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3,3,dtype=torch.long)
print(z)
# Construct a 3x3 matrix of ones
o =  torch.ones(3, 3)
print(0)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
0
torch.float32


In [97]:
print(r2)
# Convert the data type of the tensor
r2_like = torch.randn_like(r2, dtype=torch.double)
print(r2_like)

tensor([[-1.7672, -0.4486,  0.2094, -1.7813],
        [-1.7037, -0.1303,  0.2090, -2.3718],
        [-1.7970, -0.9790,  2.2273, -0.8103],
        [ 0.6536, -0.5837,  1.7950, -0.2548]])
tensor([[-0.0107, -0.9573,  0.5590, -1.9536],
        [-0.6410, -2.4402, -0.2079, -0.6323],
        [-0.3340,  0.4602,  0.3865,  2.3460],
        [-0.9019, -0.9835, -0.5100, -1.1063]], dtype=torch.float64)


In [100]:
# Add two tensors, make sure they are the same size and data type
add_results = torch.add(r, r2)
print(add_results)

tensor([[-1.4381, -0.2379,  0.7298, -1.5645],
        [-1.4445,  0.8568,  1.1589, -2.0648],
        [-0.9390, -0.5580,  2.6677, -0.2971],
        [ 1.4877,  0.3150,  2.3993, -0.1897]])


In [104]:
# In-place addition (change the value of r2)
r2.add(r)
print(r2)

tensor([[-1.7672, -0.4486,  0.2094, -1.7813],
        [-1.7037, -0.1303,  0.2090, -2.3718],
        [-1.7970, -0.9790,  2.2273, -0.8103],
        [ 0.6536, -0.5837,  1.7950, -0.2548]])


In [115]:
print(r2)
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([[-1.7672, -0.4486,  0.2094, -1.7813],
        [-1.7037, -0.1303,  0.2090, -2.3718],
        [-1.7970, -0.9790,  2.2273, -0.8103],
        [ 0.6536, -0.5837,  1.7950, -0.2548]])
tensor([-0.4486, -0.1303, -0.9790, -0.5837])
tensor([[-1.7672, -0.4486],
        [-1.7037, -0.1303],
        [-1.7970, -0.9790],
        [ 0.6536, -0.5837]])
tensor([[-1.7672, -0.4486,  0.2094, -1.7813],
        [-1.7037, -0.1303,  0.2090, -2.3718],
        [-1.7970, -0.9790,  2.2273, -0.8103]])
tensor(-0.8103)
-0.8102676868438721
tensor([-1.7970, -0.9790,  2.2273, -0.8103])
